require_relative '../../node_modules/.pnpm/@capacitor+ios@7.4.3_@capacitor+core@7.4.2/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@7.4.3_@capacitor+core@7.4.2/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@7.4.3_@capacitor+core@7.4.2/node_modules/@capacitor/ios'
  pod 'ByteowlsCapacitorFilesharer', :path => '../../node_modules/.pnpm/@byteowls+capacitor-filesharer@7.0.0_@capacitor+core@7.4.2/node_modules/@byteowls/capacitor-filesharer'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/.pnpm/@capacitor-community+admob@7.0.3/node_modules/@capacitor-community/admob'
  pod 'CapacitorCommunityNativeAudio', :path => '../../node_modules/.pnpm/@capacitor-community+native-audio@7.0.0_@capacitor+core@7.4.2/node_modules/@capacitor-community/native-audio'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@7.0.1_@capacitor+core@7.4.2/node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../node_modules/.pnpm/@capacitor+haptics@7.0.1_@capacitor+core@7.4.2/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.pnpm/@capacitor+keyboard@7.0.1_@capacitor+core@7.4.2/node_modules/@capacitor/keyboard'
  pod 'CapacitorShare', :path => '../../node_modules/.pnpm/@capacitor+share@7.0.2_@capacitor+core@7.4.2/node_modules/@capacitor/share'
  pod 'CapacitorStatusBar', :path => '../../node_modules/.pnpm/@capacitor+status-bar@7.0.1_@capacitor+core@7.4.2/node_modules/@capacitor/status-bar'
  pod 'CapawesomeCapacitorScreenOrientation', :path => '../../node_modules/.pnpm/@capawesome+capacitor-screen-orientation@7.0.2_@capacitor+core@7.4.2/node_modules/@capawesome/capacitor-screen-orientation'
  pod 'CapacitorScreenshot', :path => '../../node_modules/.pnpm/capacitor-screenshot@7.2.0_@capacitor+core@7.4.2/node_modules/capacitor-screenshot'
  pod 'CapacitorScreenOrientation', :path => '../../node_modules/.pnpm/@capacitor+screen-orientation@7.0.2_@capacitor+core@7.4.2/node_modules/@capacitor/screen-orientation'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/.pnpm/@capacitor+splash-screen@7.0.3_@capacitor+core@7.4.2/node_modules/@capacitor/splash-screen'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
